"This script fits the SEM's as described in text files provided by the user. Assumes 1_preprocessing.R
is run first. Assumes that this script will be run from the root of the repository.

Usage: 2_model.R --path_data=<path_data> --model_for_path=<model_for_path> --model_def_path=<model_def_path> --path_out=<path_out> [--m | -multilevel]

Options:
--path_data=<path_data> A file path describing where the preprocessed data is, generated by 1_preprocessing.R
--model_for_path=<model_for_path> A file path leading to a text file that describes, in lavaan syntax, the SEM to be fitted for forwards.
--model_def_path=<model_def_path> A file path leading to a text file that escribes, in lavaan syntax, the SEM to be fitted for defenceman.
--path_out=<path_out> A file path describing where to store latent factor scores and fitted models, as .rds objects.
-m --multilevel	An optional flag. Either Y/N that describes if the fitted model should me multilevel or not [default: Y].
" -> doc

library(lavaan)
library(tidyverse)
library(docopt)

opt <- docopt(doc)

#' This function extracts the latent offensive and defensive skill of all players
#' in the data used to fit the model.
#'
#' @param model A lavaan fitted model.
#' @param level If 2, return grouped estimates of latent variables 
#' (i.e. random intercept model), otherwise set to 1, which returns individual levels.
#' Will throw an error if model is not multilevel.
#' @return A tibble with columns player, off_score, and def_score.
#' @export
#'
#' @examples
#' get_latent_vars(my_lavaan_model)
get_latent_vars <- function(model, level = 2) {
	
	if (all(model@Model@multilevel == FALSE & level == 2)) {
		stop("Level = 2 but the fitted model is not multilevel. Either set level = 1 or
				 fit a multilevel model.")
	} 
	
	if (level == 2) {
		tibble(
			player = model@Data@Lp[[1]]$cluster.id[[2]],
			off_score = lavPredict(model, level = 2)[, 1],
			def_score = lavPredict(model, level = 2)[, 2]
			)
	} else {
		tibble(
			player = rep(NA, model@Data@nobs[[1]]),
			off_score = lavPredict(model, level = 1)[, 1],
			def_score = lavPredict(model, level = 1)[, 2]
		)
	}
		
}

#' Fit a lavaan model with a given model code on data from a specific year.
#'
#' @param data_file A relative path to a processed data file, most likely obtained from running 1_processed.R.
#' @param model_code A string describing a structural equation model.
#' @param position_player A string, either "D" or "F" representing the position 
#' to model.
#' @param multilevel If TRUE, fits a multilevel model. Default is TRUE. 
#' 
#' @return A list with extracted factor scores, model AIC, the actual model itself, and the data used
#' to fit the model.
#' @export
#'
#' @examples
#' fit_model_year("results/data/2015.rds", my_model_code, "F")
fit_model_year <- function(data_file, model_code, position_player, multilevel = TRUE) {
	
	data <- read_rds(paste0(data_file)) %>%
		filter(position == position_player)
	
	if (multilevel == TRUE) {
		model <- sem(model = model_code, data = data, cluster = "player")
		scores <- get_latent_vars(model, level = 2) 
	} else {
		model <- sem(model = model_code, data = data)
		scores <- get_latent_vars(model, level = 1) %>%
			mutate(player = data$player)
	}

	list(factor_scores = scores, aic = AIC(model), model = model, data = data)
	
}

main <- function(path_data, model_for_path, model_def_path, path_out, multilevel) {

	if (multilevel == "N") {
		multilevel_temp <- FALSE
	} else {
		multilevel_temp <- TRUE
	}
	
	# Read in the .txt files for the SEM models
	model_for <- read_file(paste(model_for_path))
	model_def <- read_file(paste(model_def_path))
	
	# If directory doesn't exist, create it.
	if (!dir.exists(path_out)) {
		dir.create(path_out, recursive = TRUE)
	}
	
	# Read in all of the processed data file paths
	all_processed_data_file_names <- list.files(path_data, full.names = TRUE)
	year_labels <- list.files(path_data, full.names = FALSE) %>%
		str_extract(., "[^.]+")
	
	# Fit and save model results
	all_forwards <- map(
		all_processed_data_file_names,
		.f = fit_model_year,
		model_code = model_for,
		position_player = "F",
		multilevel = multilevel_temp
		) %>%
		set_names(year_labels) %>%
		write_rds(., paste(path_out, "forwards.rds", sep = "/"))
	
	# Fit and save model results
	all_defenceman <- map(
		all_processed_data_file_names,
		.f = fit_model_year,
		model_code = model_def,
		position_player = "D",
		multilevel = multilevel_temp
		) %>%
		set_names(year_labels) %>%
		write_rds(., paste(path_out, "defenceman.rds", sep = "/"))

}

main(
	path_data = opt$path_data,
	model_for_path = opt$model_for_path,
	model_def_path = opt$model_def_path,
	path_out = opt$path_out,
	multilevel = opt$multilevel
)