"This script fits the SEM's as described in text files provided by the user. Assumes 1_preprocessing.R
is run first. Assumes that this script will be run from the root of the repository.

Usage: 2_model.R --path_data=<path_data> --model_for_path=<model_for_path> --model_def_path=<model_def_path> --path_out=<path_out>

Options:
--path_data=<path_data> A file path describing where the preprocessed data is, generated by 1_preprocessing.R
--model_for_path=<model_for_path> A file path leading to a text file that describes, in lavaan syntax, the SEM to be fitted for forwards.
--model_def_path=<model_def_path> A file path leading to a text file that escribes, in lavaan syntax, the SEM to be fitted for defenceman.
--path_out=<path_out> A file path describing where to store latent factor scores and fitted models, as .rds objects.
" -> doc

library(lavaan)
library(tidyverse)
library(docopt)

opt <- docopt(doc)

#' This function extracts the latent offensive and defensive skill of all players
#' in the data used to fit the model.
#'
#' @param model A lavaan fitted model.
#' @return A tibble with columns player, off_score, and def_score.
#' @export
#'
#' @examples
#' get_latent_vars(my_lavaan_model)
get_latent_vars <- function(model) {
	
	tibble(
		player = model@Data@Lp[[1]]$cluster.id[[2]],
		off_score = lavPredict(model, level = 2)[, 1],
		def_score = lavPredict(model, level = 2)[, 2]
		)
	
}

#' Fit a lavvaan model with a given model code on data from a specific year.
#'
#' @param data_file A relative path to a processed data file, most likely obtained from running 1_processed.R.
#' @param model_code A string describing a structural equation model.
#' @param position_player A string, either "D" or "F" representing the position 
#' to model.
#' @param path_data A file path describing where all of the preprocessed data is located.
#'
#' @return A list with extracted factor scores, model AIC, the actual model itself, and the data used
#' to fit the model.
#' @export
#'
#' @examples
#' fit_model_year("results/data/gte_2015.rds", my_model_code, "F")
fit_model_year <- function(data_file, model_code, position_player, path_data) {
	
	data <- read_rds(paste0(data_file)) %>%
		filter(position == position_player)
	
	model <- sem(model = model_code, data = data, cluster = "player")
	
	scores <- get_latent_vars(model)
	
	list(factor_scores = scores, aic = AIC(model), model = model, data = data)
	
}

main <- function(path_data, model_for_path, model_def_path, path_out) {

	# Read in the .txt files for the SEM models
	model_for <- read_file(paste(model_for_path))
	model_def <- read_file(paste(model_def_path))
	
	# If directory doesn't exist, create it.
	if (!dir.exists(path_out)) {
		dir.create(path_out)
	}
	
	# Read in all of the processed data file paths
	all_processed_data_file_names <- list.files(path_data, full.names = TRUE)
	
	# Fit and save model results
	all_forwards <- map(all_processed_data_file_names, .f = fit_model_year, model_code = model_for, position_player = "F") %>%
		set_names(2014:2019) %>%
		write_rds(., paste(path_out, "forwards.rds", sep = "/"))
	
	# Fit and save model results
	all_defenceman <- map(all_processed_data_file_names, .f = fit_model_year, model_code = model_def, position_player = "D") %>%
		set_names(2014:2019) %>%
		write_rds(., paste(path_out, "defenceman.rds", sep = "/"))

}

main(
	path_data = opt$path_data,
	model_for_path = opt$model_for_path,
	model_def_path = opt$model_def_path,
	path_out = opt$path_out
)